### ISSUE TITLE
Is it possible to add custom section in the home page?

### ISSUE THREAD

**Issue by laubonghaudoi** [zzossig/hugo-theme-zdoc#3]
Just like the docsy theme: https://example.docsy.dev/
It would be great if zdoc supports custom extra section in the home page. Btw zdoc is my favorite theme so far, please keep going!

**Comment by zzossig** [comment]
Ok, I'll try

**Comment by zzossig** [comment]
I added some sections.

This is my full test code.
You may get an idea from it.
I'll document this later on.
I'm looking forward to hearing your opinion

```yaml
---
title: Zzo
description: Hugo Zzo theme documentation landing page
date: 2020-01-26T04:15:05+09:00
draft: false
# updatesBanner: "Banner - &nbsp; [Hugo ZDoc theme](https://github.com/zzossig/hugo-theme-zdoc) &nbsp; just arrived"
landingImage: favicon/android-icon-192x192.png
landingTitle:
  - Zzo Docs
landingText:
  - Make a blog with hugo zzo theme!
titleColor:
textColor:
spaceBetweenTitleText: 25
buttons:
  - link: docs/gettingstarted/quickstart
    text: GET STARTED
    color: primary
  - link: https://github.com/zzossig/hugo-theme-zzo
    text: DOWNLOAD
    color: default
sections:
  - bgcolor: teal
    type: card
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue. Suspendisse semper laoreet tortor sed convallis. Nulla ac euismod lorem"
    header: 
      title: Why Zdoc
      hlcolor: "#8bc34a"
      color: '#fff'
      fontSize: 32
      width: 220
    cards:
      - subtitle: Performance
        subtitlePosition: center
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue."
        image: images/section/keyboard.png
        color: white
        button: 
          name: Naver
          link: https://naver.com
          size: large
          target: _blank
          color: 'white'
          bgcolor: '#283593'
      - subtitle: Reliability
        subtitlePosition: center
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue. Suspendisse semper laoreet tortor sed convallis. Nulla ac euismod lorem"
        image: images/section/processor.png
        color: white
        button: 
          name: Google
          link: https://google.com
          size: large
          target: _blank
          color: 'white'
          bgcolor: '#283593'
      - subtitle: Productivity
        subtitlePosition: center
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue. Suspendisse semper laoreet tortor sed convallis. Nulla ac euismod lorem"
        image: images/section/root-server.png
        color: white
        button: 
          name: Yahoo
          link: https://yahoo.com
          size: large
          target: _blank
          color: 'white'
          bgcolor: '#283593'
  - bgcolor: DarkSlateBlue
    type: normal
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue. Suspendisse semper laoreet tortor sed convallis. Nulla ac euismod lorem"
    header:
      title: Build it with Zdoc
      hlcolor: DarkKhaki
      color: "#fff"
      fontSize: 32
      width: 340
    body:
      subtitle: Extensible and customizable.
      subtitlePosition: left
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id eleifend erat. Integer eget mattis augue. Suspendisse semper laoreet tortor sed convallis. Nulla ac euismod lorem"
      color: white
      image: images/section/root-server.png
      imagePosition: left
---

```

**Comment by laubonghaudoi** [comment]
Yes, this works perfectly! Just like the home page on [zzodocs.netlify.com](https://zzodocs.netlify.com/) now. Please add this to the theme and document it.

There is one potential improvement though. I think the top section should cover full screen (like the docsy theme and has an arrow to indicate scrolling down for below sections), or at least should be an option for it.

**Comment by zzossig** [comment]
@laubonghaudoi
I add support background on the landing page.
We have new landing params `height`, `backgroundImage`
You can do this.

```yaml
landing:
  height: 500
 ...
  backgroundImage: 
     src: images/landscape.jpg
     height: 600
```

Also, you can set navbar menu colors.
You can find the `color.toml` file at `root/themes/data/color.toml`.
Copy-paste the file at your `root/data/color.toml` and edit the file as you want.
