### ISSUE TITLE
hide toc by default [feature request]

### ISSUE THREAD

**Issue by yukihane** [zzossig/hugo-theme-zdoc#32]
Hi.

I woud like keep main content width widely.
So, for example, when `enableToc = false`, is it possible `list-side` hidden by default ?

**Comment by zzossig** [comment]
I have added new params

```toml
wideViewAsDefault = true
enableWideBlogSwitch = true
```

Update the theme first.
You may want to set `wideViewAsDefault ` to true.
