### ISSUE TITLE
[Wishlist] Add "copy to clipboard" button to code blocks

### ISSUE THREAD

**Issue by TiagoJSilva** [zzossig/hugo-theme-zdoc#56]
I love this theme, but I'm totally failing to add a button to copy code blocks by myself. The theme code has includes to "copy-to-clipboard.min.js" scattered around, so you're probably already working on it, but something in the way the code block generation is set up breaks the positioning of the copy button for the single tutorial I found that can copy the block, https://www.tomspencer.dev/blog/2018/09/14/adding-click-to-copy-buttons-to-a-hugo-powered-blog/.
(all the others, like https://www.dannyguo.com/blog/how-to-add-copy-to-clipboard-buttons-to-code-blocks-in-hugo/,  fail on showing the button or on copying the code block contents)
I can get a copy button, and it copies the code block, but the button gets inserted in the "wrong" place, way up in the DOM instead of near the code block.

**Comment by prestonr83** [comment]
@TiagoJSilva Don't know if you figured this out but I was able to hack something together. Unfortunately, I don't know how to add custom js to the theme so I just forked it. I added this script to zdoc/layouts/partials/head/scripts.html 

```
    window.addEventListener("load", addCopyButton);
    function addCopyButton(clipboard) {
        document.querySelectorAll('pre > code').forEach(function(codeBlock) {
            if (codeBlock.className === '') {
                return
            }
            var table = codeBlock.parentNode.parentNode.parentNode.parentNode.parentNode
            var row = table.insertRow(0);
            var cell = row.insertCell();
            cell.className = "lntd"
            var cell = row.insertCell();
            cell.innerHTML = "<BR>"
            var button = document.createElement('button');
            button.className = 'copy-code-button';
            button.type = 'button';
            button.innerText = 'Copy';
            button.addEventListener('click', function() {
                if (navigator.clipboard != undefined) {//Chrome
                        navigator.clipboard.writeText(codeBlock.innerText).then(function () {
                            console.log('Async: Copying to clipboard was successful!');
                        }, function (err) {
                            console.error('Async: Could not copy text: ', err);
                        });
                    }
                    else if(window.clipboardData) { // Internet Explorer
                        window.clipboardData.setData("Text", codeBlock.innerText);
                    }
            });
            cell.appendChild(button)
        });
    }
```

**Comment by TiagoJSilva** [comment]
@prestonr83 I have probably damaged my local theme way too much for that code to work; I succeeded in making it show a copy button a single time, and it was placed nearer to what I wanted but still misplaced.
I can get the Tom Spencer code to show the button where I'd like it to be (more or less, what I'd **really** like was to get it to be inside the code block, aligned top-right, and semi-transparent going to opaque on hover :D ) with `containerEl.firstElementChild.appendChild(copyBtn)` instead of `containerEl.appendChild(copyBtn)`, but since `containerEl.firstElementChild` is the node that is going to be copied, the "Copy" text gets put in the clipboard as well, and I can't edit the `var range` or the `var selection` to trim those 4 characters. To recap, here's the gist of Tom Spencer's code in `layouts/partials/script/codeblock-script.html`:
```
(function() {
  'use strict';

  if(!document.queryCommandSupported('copy')) {
    return;
  }

  function flashCopyMessage(el, msg) {
    el.textContent = msg;
    setTimeout(function() {
      el.textContent = "Copy";
    }, 1000);
  }
  
function selectText(node) {
    var selection = window.getSelection();
    var range = document.createRange();
    range.selectNodeContents(node);
    selection.removeAllRanges();
    selection.addRange(range);
    return selection;
  }

  function addCopyButton(containerEl) {
    var copyBtn = document.createElement("button");
    copyBtn.className = "highlight-copy-btn";
    copyBtn.textContent = "Copy";

    var codeEl = containerEl.firstElementChild;
    copyBtn.addEventListener('click', function() {
      try {
        var selection = selectText(codeEl);
        document.execCommand('copy');
        selection.removeAllRanges();

        flashCopyMessage(copyBtn, 'Copied!')
      } catch(e) {
        console && console.log(e);
        flashCopyMessage(copyBtn, 'Failed :\'(')
      }
    });

  containerEl.appendChild(copyBtn);
  }

  // Add copy button to code blocks
  var highlightBlocks = document.getElementsByClassName('highlight');
  for (var i = 0; i < highlightBlocks.length; i++) {
    addCopyButton(highlightBlocks[i]);
  }
})();
```
I don't know enough JS to convert that `var selection` to a string, substring it to remove the `copyBtn.TextContent` and then copy the string to the clipboard. Or doing it inside `selectText()`: convert the Range to a string, modify the string, return the corrected string instead of a "selection", and modify the `try{}` block if `var selection` doesn't accept the assignment of the returned string value.
[edit to add] - maybe replacing the button text with an image? Can't be a glyph, otherwise it'll be copied as well; as long as the URL to the button-image isn't copied as part of the text...[/edit]

**Comment by TiagoJSilva** [comment]
OK, with Tom Spencer's code above, I can adapt some CSS I copied from some source (sorry, didn't make a note of my source, this code isn't mine) to put the button where I'd like it to be, even with `containerEl.appendChild(copyBtn);`
The following was put in `assets/sass/pages/_single.scss`
```scss
 .highlight-copy-btn {
  position: relative;
  bottom: 20px;
  right: 0px;
  border: 0;
  border-radius: 4px;
  padding: 1px;
  font-size: 0.7em;
  line-height: 1.8;
  opacity: 0.6;
  min-width: 55px;
  text-align: center;
  @include themify($codeblock) {
    color: themed('content-pre-color');
    background: themed('content-pre-background-color');
    border: 1.25px solid themed('border-line-color');
  }
  border-top-left-radius: 0;
  border-top-right-radius: 4px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 4px;
  white-space: nowrap;
  padding: 4px 4px 5px 4px;
  margin: 0 0 0 1px;
  cursor: pointer;
  opacity: 0.6;
}

.highlight-copy-btn:hover {
// this BG color doesn't work with the bright mode, I need to themefy it too
  background-color: #666;
}
```
The button is now below the code block and on the left margin, and visually it looks like it belongs with that code block.
But I realize now that I should find a way of inserting this button on all code blocks and not just those where syntax formatting has been activated (`<div class="highlight">`).
They are handled very differently by Zdoc.
Maybe I need to add similar code somewhere else (or try your code again) to get all the "regular" MarkDown codeblocks (or codeblocks for which Zdoc doesn't catch the syntax)
I need to catch the `<pre><code>`  elements for those.
